# Generated by Django 4.1.7 on 2024-08-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateurs",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Images/Photos/Utilisateurs/",
                verbose_name="photo de profil",
            ),
        ),
    ]
