# Generated by Django 4.1.7 on 2024-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_utilisateurs_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateurs",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Mediatheques/",
                verbose_name="photo de profil",
            ),
        ),
    ]
