# Generated by Django 4.1.7 on 2024-09-14 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=200)),
                ("telephone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "apport",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "pourcentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("date_adhesion", models.DateField(auto_now_add=True)),
                (
                    "dividende",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=200)),
                ("telephone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CallHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("call_date", models.DateTimeField(auto_now_add=True)),
                ("call_duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, null=True)),
                ("prenom", models.CharField(max_length=100, null=True)),
                ("adresse", models.CharField(max_length=200, null=True)),
                ("telephone", models.CharField(max_length=20, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("date_inscription", models.DateField(auto_now_add=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                (
                    "piece_identite_scan",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=100, null=True)),
                (
                    "type_piece_identite",
                    models.CharField(
                        choices=[
                            ("CNI", "Carte Nationale d'Identité"),
                            ("passeport", "Passeport"),
                            ("Attestation", "Attestation d'identité"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero_piece_identite", models.CharField(max_length=100, null=True)),
                ("validite_piece_identite_debut", models.DateField()),
                ("validite_piece_identite_fin", models.DateField()),
                ("ville_village", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesolde", models.DateField()),
                (
                    "soldeprecedent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_aide", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteAdhesionkhas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesolde", models.DateField()),
                (
                    "soldeprecedent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateprecedent", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompteEpargnes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_compte", models.CharField(max_length=20, unique=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("naturecompte", models.CharField(max_length=20, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.clients",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteEpargnesact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_compte", models.CharField(max_length=20, unique=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "actionnaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.actionnaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteFondateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesolde", models.DateField()),
                (
                    "soldeprecedent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateprecedent", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompteInterets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesolde", models.DateField()),
                (
                    "soldeprecedent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateprecedent", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompteKha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesolde", models.DateField()),
                (
                    "soldeprecedent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateprecedent", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComptePenalites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesolde", models.DateField()),
                (
                    "soldeprecedent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateprecedent", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComptePrets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_compte", models.CharField(max_length=20, unique=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taux_interet",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("duree_en_mois", models.PositiveIntegerField(default=12)),
                ("date_debut_pret", models.DateField()),
                ("date_fin_pret", models.DateField()),
                (
                    "somme_initiale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("domicile_bancaire", models.CharField(max_length=200, null=True)),
                ("date_demande", models.DateField(auto_now_add=True, null=True)),
                ("naturecompte", models.CharField(max_length=20, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.clients",
                    ),
                ),
                (
                    "com",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComptePretsact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_compte", models.CharField(max_length=20, unique=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taux_interet",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("duree_en_mois", models.PositiveIntegerField(default=12)),
                ("date_debut_pret", models.DateField()),
                ("date_fin_pret", models.DateField()),
                (
                    "somme_initiale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("domicile_bancaire", models.CharField(max_length=200, null=True)),
                ("date_demande", models.DateField(auto_now_add=True, null=True)),
                (
                    "actionnaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.actionnaire",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "com",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Demandes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_dde", models.DateTimeField(auto_now_add=True)),
                ("Nom_prenoms", models.CharField(max_length=250, unique=True)),
                ("deja_beneficie", models.CharField(max_length=20)),
                ("nombrefois", models.CharField(max_length=20)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("lieuhabitation", models.CharField(max_length=20)),
                ("typedde", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Echeancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_echeance", models.DateField()),
                (
                    "montant_echeance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "montant_interet",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("est_paye", models.BooleanField(default=False)),
                (
                    "montant_epargne",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "montant_adhesion",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "montant_penalite",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "ancien_echeance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "compte_pret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.compteprets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Echeancieract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_echeance", models.DateField()),
                (
                    "montant_echeance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "montant_interet",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("est_paye", models.BooleanField(default=False)),
                (
                    "montant_epargne",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "montant_adhesion",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "montant_penalite",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "ancien_echeance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "compte_pretact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.comptepretsact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sexe", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("license_key", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Matrimoniales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrimoniale", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_msg", models.DateTimeField(auto_now_add=True)),
                ("titre", models.CharField(max_length=20, unique=True)),
                ("message", models.CharField(max_length=2000)),
                ("groupemsg", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Natclients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nat_client", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("contact", models.CharField(max_length=15)),
                ("presentation_text", models.TextField()),
                ("welcome_message", models.TextField()),
                (
                    "video_url",
                    models.FileField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("site", models.CharField(max_length=50, null=True)),
                (
                    "pub",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("email", models.CharField(max_length=50, null=True)),
                ("whatsapp", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Statuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statut", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tontines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tontine", models.CharField(max_length=20, unique=True)),
                ("date_tontine", models.DateField(auto_now_add=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cotite",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("nbreaide", models.PositiveIntegerField(default=0)),
                ("penaliteton", models.PositiveIntegerField(default=0)),
                (
                    "montant_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_palier", models.DateField(null=True)),
                ("duree", models.PositiveIntegerField(default=0)),
                ("dateaide", models.DateField(null=True)),
                (
                    "montant_aide",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_futurcotisation", models.DateField(null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.clients",
                    ),
                ),
                (
                    "com",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.agent",
                    ),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.statuts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Typeactionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_act", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Typeagent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_agent", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Typeclients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_client", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Typedocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Typedoc", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Typeprets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_pret", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Typetontines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_tontine", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTontine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                            ("Mobile money", "Mobile money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tontine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_tontine",
                        to="finances.tontines",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionRistourne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[("Depot", "Dépôt"), ("Retrait", "Retrait")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "actionnaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_ristourne",
                        to="finances.actionnaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPretact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compte_pret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_pret",
                        to="finances.comptepretsact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compte_pret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_pret",
                        to="finances.compteprets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPenaliteHist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "comptepenalite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_penalite",
                        to="finances.comptepenalites",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPenaliteact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "compte_pret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_penaliteact",
                        to="finances.comptepretsact",
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_penaliteact",
                        to="finances.echeancieract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPenalite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "compte_pret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_penalite",
                        to="finances.compteprets",
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_penalite",
                        to="finances.echeancier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionKha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comptekha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_kha",
                        to="finances.comptekha",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInteret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "compteinteret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_interet",
                        to="finances.compteinterets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionFondateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comptefond",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_adhesionkha",
                        to="finances.comptefondateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionEpargneact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compte_epargne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_epargneact",
                        to="finances.compteepargnesact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionEpargne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compte_epargne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_epargne",
                        to="finances.compteepargnes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionCommissionpret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                            ("Mobile money", "Mobile money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_commpret",
                        to="finances.commissions",
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_comm",
                        to="finances.echeancier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionCommissioninves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                            ("Mobile money", "Mobile money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "actionnaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_commact",
                        to="finances.actionnaire",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commissioninv",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_cominves",
                        to="finances.commissions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionAdhesionkha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compteAdhessionkha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_adhesion",
                        to="finances.compteadhesionkhas",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tontines",
            name="type_tontine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typetontines",
            ),
        ),
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=200)),
                ("telephone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "apport",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "pourcentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("date_adhesion", models.DateTimeField(auto_now_add=True)),
                (
                    "dividende",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "type_act",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.typeactionnaire",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rachatsact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rachat", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_actuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reste_actuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("compte_pretnew", models.CharField(max_length=100)),
                (
                    "montant_new",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "actionnaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.actionnaire",
                    ),
                ),
                (
                    "compte_pretactuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.comptepretsact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rachats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rachat", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_actuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reste_actuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("compte_pretnew", models.CharField(max_length=100)),
                (
                    "montant_new",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.clients",
                    ),
                ),
                (
                    "compte_pretactuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.compteprets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("File", models.FileField(upload_to="Mediatheques/")),
                (
                    "Typedoc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.typedocuments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contratsponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_contrat", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100, null=True)),
                ("prenom", models.CharField(max_length=100, null=True)),
                ("adresse", models.CharField(max_length=200, null=True)),
                ("telephone", models.CharField(max_length=20, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("date_inscription", models.DateField(auto_now_add=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                (
                    "piece_identite_scan",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                ("date_naissance", models.DateField(null=True)),
                ("lieu_naissance", models.CharField(max_length=100, null=True)),
                (
                    "type_piece_identite",
                    models.CharField(
                        choices=[
                            ("CNI", "Carte Nationale d'Identité"),
                            ("passeport", "Passeport"),
                            ("Attestation", "Attestation d'identité"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("numero_piece_identite", models.CharField(max_length=100, null=True)),
                ("validite_piece_identite_debut", models.DateField(null=True)),
                ("validite_piece_identite_fin", models.DateField(null=True)),
                ("ville_village", models.CharField(max_length=100, null=True)),
                ("numero_compte", models.CharField(max_length=20, unique=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taux_interet",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("duree_en_mois", models.PositiveIntegerField(default=12)),
                ("duree_contrat", models.PositiveIntegerField(default=12, null=True)),
                ("date_fin_contrat", models.DateField(null=True)),
                (
                    "soldecontrat",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("date_debut_pret", models.DateField()),
                ("date_fin_pret", models.DateField()),
                (
                    "somme_initiale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("domicile_bancaire", models.CharField(max_length=200, null=True)),
                ("date_demande", models.DateField(auto_now_add=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.clients",
                    ),
                ),
                (
                    "com",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.agent",
                    ),
                ),
                (
                    "matrimoniale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.matrimoniales",
                    ),
                ),
                (
                    "nat_client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.natclients",
                    ),
                ),
                (
                    "sexe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.genres",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.sponsors",
                    ),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.statuts",
                    ),
                ),
                (
                    "type_client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.typeclients",
                    ),
                ),
                (
                    "type_pret",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.typeprets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Confconstantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partrespo",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partactif",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partnonactif",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partpalierun",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partpalierd",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partparliert",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partparlierq",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partparlierc",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partfraisdos",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partfraisdossous",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partcom",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partpenalite",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partepargne",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partepargnesous",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "partdemarch",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("dureecoopa", models.PositiveIntegerField(default=0)),
                ("dureecoopn", models.PositiveIntegerField(default=0)),
                (
                    "partprelev",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.statuts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComptePrincipale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datecapital", models.DateField(auto_now_add=True)),
                (
                    "totalentree",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateentree", models.DateField(auto_now_add=True)),
                (
                    "totalsortie",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datesortie", models.DateField(auto_now_add=True)),
                (
                    "totalgain",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dategain", models.DateField(auto_now_add=True)),
                (
                    "totaldepenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("datedepense", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.statuts",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comptepretsact",
            name="statut",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finances.statuts"
            ),
        ),
        migrations.AddField(
            model_name="comptepretsact",
            name="type_client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typeclients",
            ),
        ),
        migrations.AddField(
            model_name="comptepretsact",
            name="type_pret",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typeprets",
            ),
        ),
        migrations.AddField(
            model_name="compteprets",
            name="statut",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finances.statuts"
            ),
        ),
        migrations.AddField(
            model_name="compteprets",
            name="type_client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typeclients",
            ),
        ),
        migrations.AddField(
            model_name="compteprets",
            name="type_pret",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typeprets",
            ),
        ),
        migrations.CreateModel(
            name="ComptePortefeuilles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totalentree",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "totalsortie",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "totalreste",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.statuts",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comptepenalites",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="comptekha",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="compteinterets",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="comptefondateur",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="compteepargnesact",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="compteepargnes",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="compteadhesionkhas",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="commissions",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="clients",
            name="matrimoniale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.matrimoniales",
            ),
        ),
        migrations.AddField(
            model_name="clients",
            name="nat_client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.natclients",
            ),
        ),
        migrations.AddField(
            model_name="clients",
            name="sexe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.genres",
            ),
        ),
        migrations.AddField(
            model_name="clients",
            name="statut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.statuts",
            ),
        ),
        migrations.AddField(
            model_name="clients",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Aides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_aide", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_aide",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.clients",
                    ),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.statuts",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="type_agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typeagent",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="actionnaire",
            name="com",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.agent",
            ),
        ),
        migrations.AddField(
            model_name="actionnaire",
            name="type_act",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.typeactionnaire",
            ),
        ),
        migrations.AddField(
            model_name="actionnaire",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
