# Generated by Django 4.1.7 on 2024-09-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0003_alter_echeancier_ancien_echeance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCommissionpretact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                            ("Mobile money", "Mobile money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commissionact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_commpretact",
                        to="finances.commissions",
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_comm",
                        to="finances.echeancieract",
                    ),
                ),
            ],
        ),
    ]
