# Generated by Django 4.1.7 on 2024-09-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_transactioncommissionpretact"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRetraitsponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "Motif",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "gain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_retraitgain",
                        to="finances.sponsors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionRetraitdemarcheur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "Motif",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "dem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_retraitdem",
                        to="finances.commissions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionRetraitcommercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "Motif",
                    models.CharField(
                        choices=[
                            ("Depot", "Dépôt"),
                            ("Retrait", "Retrait"),
                            ("Virement", "Virement"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "com",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_retraitcom",
                        to="finances.commissions",
                    ),
                ),
            ],
        ),
    ]
