# Generated by Django 4.1.7 on 2024-09-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0005_transactionretraitsponsor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionpenalitehist",
            name="comptepenalite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_penal",
                to="finances.comptepenalites",
            ),
        ),
    ]
