# Generated by Django 4.1.7 on 2024-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0006_alter_transactionpenalitehist_comptepenalite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionretraitcommercial",
            name="Motif",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="transactionretraitdemarcheur",
            name="Motif",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="transactionretraitsponsor",
            name="Motif",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
